# _config_local.yml
# This tells Jekyll to ignore the remote theme and use the local gem instead
theme: just-the-docs
remote_theme: null
plugins: []

sass:
  style: compressed
  quiet_deps: true
  silence_deprecations:
    - import
    - color-functions
    - global-builtin