title: Async Conveyor Plugin
description: Documentation for the Async Conveyor Plugin for Unreal Engine 5, for version 3.0 of the plugin and above
theme: just-the-docs
favicon_ico: /assets/images/icon.svg
color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  important:
    title: Important!
    color: red
  advanced:
    title: Advanced
    color: grey-lt

url: https://theuntextured.github.io/AsyncConveyorPlugin/

aux_links:
  FAB Plugin: https://www.fab.com/listings/7ebfd4f3-eec3-4204-82aa-98b7ff01ec5f
  v2.0 Docs: https://github.com/Theuntextured/AsyncConveyorPlugin/wiki
