title: Async Conveyor Plugin
description: Documentation for the Async Conveyor Plugin for Unreal Engine 5, for version 3.0 of the plugin and above

remote_theme: just-the-docs/just-the-docs
#theme: just-the-docs

plugins:
  - jekyll-remote-theme
favicon_ico: /assets/images/icon.svg
color_scheme: dark

logo: /assets/images/logo.png

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  important:
    title: Important!
    color: red
  advanced:
    title: Advanced
    color: grey-lt
  todo:
    title: TO-DO! (NOTE TO SELF)
    color: purple

baseurl: /AsyncConveyorPlugin
url: https://theuntextured.github.io

permalink: pretty

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

aux_links:
  FAB Plugin: https://www.fab.com/listings/7ebfd4f3-eec3-4204-82aa-98b7ff01ec5f
  v2.0 Docs: https://github.com/Theuntextured/AsyncConveyorPlugin/wiki

aux_links_new_tab: true

search_enabled: true
search:
  # Split the search index into smaller chunks if you have a massive site
  tokenizer_separator: /[\s/]+/
  # Display the full URL in search results
  rel_url: true
  # Highlight search terms
  heading_level: 3
  previews: 3

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/
  - spec/
  - tmp
  - .rspec
  - LICENCE
  - Build.bat

